Repository infrawatch/documentation, pull requests merged in 2019-10, with the labels that each got.

#3 Provide ability to build documentation
  .gitignore
  Makefile
  doc-Service-Assurance-Framework/Makefile
Labels: invalid

#5 Provide auto building of documentation and publishing to gh-pages
  .travis.yml
  build_tools/travis.sh
  doc-Service-Assurance-Framework/Makefile
Labels: enhancement

#7 Create a BRANCH env var holding git branch
  .travis.yml
  build_tools/travis.sh
Labels: bug

#22 Change invalid OpenShiftLong to OpenShift
  doc-Service-Assurance-Framework/modules/con_architecture.adoc
  doc-Service-Assurance-Framework/modules/con_installation-size.adoc
  doc-Service-Assurance-Framework/modules/con_overview-of-service-assurance-framework.adoc
Labels: bug

#23 Minor text edits
  common/attributes.adoc
  doc-Service-Assurance-Framework/assemblies/assembly_completing-the-saf-configuration.adoc
  doc-Service-Assurance-Framework/assemblies/assembly_configuring-saf-components.adoc
  doc-Service-Assurance-Framework/assemblies/assembly_connecting-multiple-clouds-to-saf.adoc
  doc-Service-Assurance-Framework/assemblies/assembly_installing-the-core-components-of-saf.adoc
  doc-Service-Assurance-Framework/modules/con_conclusion.adoc
  doc-Service-Assurance-Framework/modules/con_the-core-components-of-saf.adoc
  doc-Service-Assurance-Framework/modules/proc_configuring-multiple-clouds.adoc
  doc-Service-Assurance-Framework/modules/proc_configuring-red-hat-openstack-platform-overcloud-for-saf-events.adoc
  doc-Service-Assurance-Framework/modules/proc_configuring-red-hat-openstack-platform-overcloud-for-saf.adoc
  doc-Service-Assurance-Framework/modules/proc_creating-an-rhcc-secret.adoc
  doc-Service-Assurance-Framework/modules/proc_deleting-the-default-smart-gateways.adoc
  doc-Service-Assurance-Framework/modules/proc_deploying-saf-to-the-openshift-environment.adoc
  doc-Service-Assurance-Framework/modules/proc_deploying-smart-gateways.adoc
  doc-Service-Assurance-Framework/modules/proc_deploying-with-routed-l3-networks.adoc
  doc-Service-Assurance-Framework/modules/proc_generating-a-tls-certificate-for-amq-interconnect.adoc
  doc-Service-Assurance-Framework/modules/proc_generating-tls-certificates-for-elasticsearch.adoc
  doc-Service-Assurance-Framework/modules/proc_importing-the-container-images-for-saf.adoc
  doc-Service-Assurance-Framework/modules/proc_planning-amqp-address-prefixes.adoc
  doc-Service-Assurance-Framework/modules/proc_preparing-your-openshift-environment-for-saf.adoc
  doc-Service-Assurance-Framework/modules/proc_prerequisites-for-saf-deployment.adoc
  doc-Service-Assurance-Framework/modules/proc_setting-up-openstack-on-the-client-side.adoc
  doc-Service-Assurance-Framework/modules/proc_updating-collectd-configuration.adoc
  doc-Service-Assurance-Framework/modules/proc_updating-red-hat-openstack-platform-overcloud-for-saf.adoc
  doc-Service-Assurance-Framework/modules/proc_using-the-amq-interconnect-message-bus.adoc
  doc-Service-Assurance-Framework/modules/ref_example-manifests.adoc
Labels: ready for merge

#25 Fix formatting of the collectd appendix
  common/collectd/ref_collectd-plugins.adoc
Labels: bug
