Repository infrawatch/documentation, pull requests merged in 2021-07, with the labels that each got.

#227 Configure sensubility to publish to new address
  doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file-for-multiple-clouds.adoc
Labels: 1.3, needs-backport

#228 Configure sensubility to publish to new address
  doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
Labels: 1.2, cherry-pick

#231 Use the stable tag for STF CatalogSource
  doc-Service-Telemetry-Framework/modules/proc_subscribing-to-the-amq-certificate-manager-operator.adoc
Labels: 1.3, cherry-pick

#230 Use the stable tag for STF CatalogSource
  doc-Service-Telemetry-Framework/modules/proc_subscribing-to-the-amq-certificate-manager-operator.adoc
Labels: 1.2, cherry-pick

#240 Adjust multi-cloud config to avoid extra topics
  doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file-for-multiple-clouds.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-the-base-configuration-for-stf.adoc
  doc-Service-Telemetry-Framework/modules/proc_querying-metrics-data-from-multiple-clouds.adoc
Labels: 1.3, needs-backport, ready for tech writer

#241 Adjust multi-cloud config to avoid extra topics (#240)
  doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file-for-multiple-clouds.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-the-base-configuration-for-stf.adoc
  doc-Service-Telemetry-Framework/modules/proc_querying-metrics-data-from-multiple-clouds.adoc
Labels: 1.3, cherry-pick

#239 Updates for new sensubility amqp1 address
  doc-Service-Telemetry-Framework/modules/proc_creating-the-base-configuration-for-stf.adoc
  doc-Service-Telemetry-Framework/modules/proc_deploying-smart-gateways.adoc
  doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
  doc-Service-Telemetry-Framework/modules/proc_planning-amqp-address-prefixes.adoc
Labels: 1.3, needs-backport, ready for tech writer

#242 Updates for new sensubility amqp1 address (#239)
  doc-Service-Telemetry-Framework/modules/proc_creating-the-base-configuration-for-stf.adoc
  doc-Service-Telemetry-Framework/modules/proc_deploying-smart-gateways.adoc
  doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
  doc-Service-Telemetry-Framework/modules/proc_planning-amqp-address-prefixes.adoc
Labels: 1.3, cherry-pick

#244 Enable Ceilometer events
  doc-Service-Telemetry-Framework/modules/proc_creating-the-base-configuration-for-stf.adoc
Labels: 1.3, needs-backport

#245 Enable Ceilometer events (#244)
  doc-Service-Telemetry-Framework/modules/proc_creating-the-base-configuration-for-stf.adoc
Labels: 1.3, cherry-pick

#246 Update dashboard import paths for stf-1.3
  doc-Service-Telemetry-Framework/modules/proc_importing-dashboards.adoc
Labels: 1.3, needs-backport

#248 Update dashboard import paths for stf-1.3 (#246)
  doc-Service-Telemetry-Framework/modules/proc_importing-dashboards.adoc
Labels: 1.3, cherry-pick

#252 Allow better build controls in Makefile (#250)
  Makefile
Labels: 1.3, cherry-pick

#251 Allow better build controls in Makefile (#250)
  Makefile
  doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file.adoc
Labels: 1.2, cherry-pick

#253 Drop erroneous usage of subs +quotes in asciidoc
  doc-Service-Telemetry-Framework/modules/proc_configuring-the-stf-connection-for-the-overcloud.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-a-route-in-ocp.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-a-servicetelemetry-object-in-openshift.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file-for-multiple-clouds.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-the-base-configuration-for-stf.adoc
  doc-Service-Telemetry-Framework/modules/proc_deploying-the-overcloud.adoc
  doc-Service-Telemetry-Framework/modules/proc_enabling-infrawatch-catalog-source.adoc
  doc-Service-Telemetry-Framework/modules/proc_sending-metrics-to-gnocchi-and-to-stf.adoc
  doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
  doc-Service-Telemetry-Framework/modules/proc_subscribing-to-the-amq-certificate-manager-operator.adoc
  doc-Service-Telemetry-Framework/modules/proc_subscribing-to-the-elastic-cloud-on-kubernetes-operator.adoc
  doc-Service-Telemetry-Framework/modules/proc_subscribing-to-the-service-telemetry-operator.adoc
Labels: 1.2, 1.3, needs-backport

#254 stf13/cp 397391757009ee7ea94ebf0286329340e468a636
  doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-3.adoc
  doc-Service-Telemetry-Framework/modules/proc_configuring-the-stf-connection-for-the-overcloud.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-a-route-in-ocp.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-a-servicetelemetry-object-in-openshift.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file-for-multiple-clouds.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-the-base-configuration-for-stf.adoc
  doc-Service-Telemetry-Framework/modules/proc_deploying-the-overcloud.adoc
  doc-Service-Telemetry-Framework/modules/proc_enabling-infrawatch-catalog-source.adoc
  doc-Service-Telemetry-Framework/modules/proc_sending-metrics-to-gnocchi-and-to-stf.adoc
  doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
  doc-Service-Telemetry-Framework/modules/proc_subscribing-to-the-amq-certificate-manager-operator.adoc
  doc-Service-Telemetry-Framework/modules/proc_subscribing-to-the-elastic-cloud-on-kubernetes-operator.adoc
  doc-Service-Telemetry-Framework/modules/proc_subscribing-to-the-service-telemetry-operator.adoc
Labels: 1.3, cherry-pick

#255 Minor fixes to OSP13 base configuration
  doc-Service-Telemetry-Framework/modules/proc_creating-the-base-configuration-for-stf.adoc
Labels: 1.3, needs-backport

#256 Minor fixes to OSP13 base configuration (#255)
  doc-Service-Telemetry-Framework/modules/proc_creating-the-base-configuration-for-stf.adoc
Labels: 1.3, cherry-pick

#258 Minor fixes for formatting and version control (#257)
  doc-Service-Telemetry-Framework/modules/proc_creating-a-servicetelemetry-object-in-openshift.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file-for-multiple-clouds.adoc
Labels: 1.3, cherry-pick

#259 Add back in note about support for OCP nextVersion
  doc-Service-Telemetry-Framework/assemblies/assembly_installing-the-core-components-of-stf.adoc
  doc-Service-Telemetry-Framework/assemblies/assembly_introduction-to-stf.adoc
  doc-Service-Telemetry-Framework/modules/con_stf-architecture.adoc
Labels: 1.3, needs-backport

#260 Add back in note about support for OCP nextVersion (#259)
  doc-Service-Telemetry-Framework/assemblies/assembly_installing-the-core-components-of-stf.adoc
  doc-Service-Telemetry-Framework/assemblies/assembly_introduction-to-stf.adoc
  doc-Service-Telemetry-Framework/modules/con_stf-architecture.adoc
Labels: 1.3, cherry-pick
