Repository infrawatch/documentation, pull requests merged in 2021-08, with the labels that each got.

#262 Fix a broken link
  doc-Service-Telemetry-Framework/modules/con_overview-of-the-servicetelemetry-object.adoc
Labels: 1.3, 1.2, needs-backport

#264 Fix a broken link (#262)
  doc-Service-Telemetry-Framework/modules/con_overview-of-the-servicetelemetry-object.adoc
Labels: cherry-pick, 1.3

#263 Fix a broken link (#262)
  doc-Service-Telemetry-Framework/modules/con_overview-of-the-servicetelemetry-object.adoc
Labels: cherry-pick, 1.2

#272 Add note about not supporting multiple clouds in the dashboards
  doc-Service-Telemetry-Framework/modules/proc_importing-dashboards.adoc
Labels: 1.3, 1.2, needs-backport

#274 Add note about not supporting multiple clouds in the dashboards (#272)
  doc-Service-Telemetry-Framework/modules/proc_importing-dashboards.adoc
Labels: cherry-pick, 1.3
