Repository infrawatch/documentation, pull requests merged in 2021-09, with the labels that each got.

#275 We should never set presettle to true
  doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file-for-multiple-clouds.adoc
Labels: 1.3, needs-backport

#277 We should never set presettle to true
  doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file.adoc
Labels: cherry-pick, 1.2

#276 We should never set presettle to true (#275)
  doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file-for-multiple-clouds.adoc
Labels: cherry-pick, 1.3

#270 Warn users that they may need to upgrade the Grafana image
  doc-Service-Telemetry-Framework/modules/proc_importing-dashboards.adoc
  doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
Labels: invalid, needs-backport

#279 Warn users that they may need to upgrade the Grafana image (#270)
  doc-Service-Telemetry-Framework/modules/proc_importing-dashboards.adoc
  doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
Labels: cherry-pick, 1.3

#287 Only show gnocchi + STF configuration for OSP16+
  doc-Service-Telemetry-Framework/assemblies/assembly_completing-the-stf-configuration.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-the-base-configuration-for-stf.adoc
Labels: 1.3, needs-backport

#289 Only show gnocchi + STF configuration for OSP16+
  doc-Service-Telemetry-Framework/assemblies/assembly_completing-the-stf-configuration.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-the-base-configuration-for-stf.adoc
Labels: cherry-pick, 1.3

#290 Use AMQ Certificate Manager from redhat-operators CatalogSource
  doc-Service-Telemetry-Framework/modules/proc_subscribing-to-the-amq-certificate-manager-operator.adoc
Labels: 1.3, needs-backport

#292 Use ECK from Certified Operators CatalogSource
  doc-Service-Telemetry-Framework/modules/proc_subscribing-to-the-elastic-cloud-on-kubernetes-operator.adoc
Labels: 1.3, needs-backport

#291 Use AMQ Certificate Manager from redhat-operators CatalogSource
  doc-Service-Telemetry-Framework/modules/proc_subscribing-to-the-amq-certificate-manager-operator.adoc
Labels: cherry-pick, 1.3

#293 Use ECK from Certified Operators CatalogSource
  doc-Service-Telemetry-Framework/modules/proc_subscribing-to-the-elastic-cloud-on-kubernetes-operator.adoc
Labels: cherry-pick, 1.3

#301 Describe the sensubility Smart Gateway object in the ServiceTelemetry manifest
  doc-Service-Telemetry-Framework/modules/con_primary-parameters-of-the-servicetelemetry-object.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-a-servicetelemetry-object-in-openshift.adoc
Labels: 1.3, needs-backport

#303 Update console output in verification sections
  doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
  doc-Service-Telemetry-Framework/modules/proc_subscribing-to-the-service-telemetry-operator.adoc
Labels: 1.3

#302 Describe the sensubility Smart Gateway object in the ServiceTelemetry manifest (#301)
  doc-Service-Telemetry-Framework/modules/con_primary-parameters-of-the-servicetelemetry-object.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-a-servicetelemetry-object-in-openshift.adoc
Labels: cherry-pick, 1.3

#304 Add virtual machine view dashboard to import documentation
  doc-Service-Telemetry-Framework/modules/proc_importing-dashboards.adoc
Labels: 1.3, needs-backport

#305 Add virtual machine view dashboard to import documentation
  doc-Service-Telemetry-Framework/modules/proc_importing-dashboards.adoc
Labels: cherry-pick, 1.3
