Repository infrawatch/documentation, pull requests merged in 2022-12, with the labels that each got.

#407 Add procedure to disable services on OSP side
  doc-Service-Telemetry-Framework/assemblies/assembly_completing-the-stf-configuration.adoc
  doc-Service-Telemetry-Framework/modules/proc_disabling-openstack-services-used-with-stf.adoc
Labels: ready for tech writer, needs-backport, 1.5

#410 Add procedure to disable services on OSP side (#407)
  doc-Service-Telemetry-Framework/assemblies/assembly_completing-the-stf-configuration.adoc
  doc-Service-Telemetry-Framework/modules/proc_disabling-openstack-services-used-with-stf.adoc
Labels: cherry-pick, 1.5

#408 Reference stable-1.5 channel and nightly-1.5 tags
  doc-Service-Telemetry-Framework/modules/proc_deploying-stf-to-the-openshift-environment.adoc
Labels: 1.5

#409 Build and push documentation for STF 1.5
  build_tools/ci.sh
  doc-Service-Telemetry-Framework/Makefile
Labels: 1.5

#411 Don't remove existing 'master' generated files
  build_tools/ci.sh
Labels: 1.5

#413 Minor updates to dashboarding guide
  doc-Service-Telemetry-Framework/modules/con_dashboards.adoc
  doc-Service-Telemetry-Framework/modules/proc_importing-dashboards.adoc
  doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
Labels: ready for tech writer, needs-backport, 1.5

#415 Minor updates to dashboarding guide (#413)
  doc-Service-Telemetry-Framework/modules/con_dashboards.adoc
  doc-Service-Telemetry-Framework/modules/proc_importing-dashboards.adoc
  doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
Labels: cherry-pick, 1.5

#416 Fix syntax error in certificate renewal module
  common/global/stf-attributes.adoc
  doc-Service-Telemetry-Framework/modules/proc_updating-the-amq-interconnect-ca-certificate.adoc
Labels: needs-backport, 1.4, 1.5

#414 Removed sending-metrics-to-gnocchi-and-to-stf m…
  .gitignore
  doc-Service-Telemetry-Framework/assemblies/assembly_completing-the-stf-configuration.adoc
  doc-Service-Telemetry-Framework/assemblies/assembly_installing-the-core-components-of-stf.adoc
  doc-Service-Telemetry-Framework/master.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-the-base-configuration-for-stf.adoc
  doc-Service-Telemetry-Framework/modules/proc_disabling-openstack-services-used-with-stf.adoc
  doc-Service-Telemetry-Framework/modules/proc_sending-metrics-to-gnocchi-and-to-stf.adoc
Labels: documentation, cherry-pick

#417 Fix syntax error in certificate renewal module (#416)
  common/global/stf-attributes.adoc
  doc-Service-Telemetry-Framework/modules/proc_updating-the-amq-interconnect-ca-certificate.adoc
Labels: cherry-pick, 1.5

#420 Fix syntax error in certificate renewal module (#416)
  common/stf-attributes.adoc
  doc-Service-Telemetry-Framework/modules/proc_updating-the-amq-interconnect-ca-certificate.adoc
Labels: cherry-pick, 1.4

#423 Update link to STF life cycle page
  doc-Service-Telemetry-Framework/modules/con_support-for-stf.adoc
Labels: needs-backport, 1.4, 1.5

#424 Update link to STF life cycle page (#423)
  doc-Service-Telemetry-Framework/modules/con_support-for-stf.adoc
Labels: cherry-pick, 1.5

#425 Update link to STF life cycle page (#423)
  doc-Service-Telemetry-Framework/modules/con_support-for-stf.adoc
Labels: cherry-pick, 1.4
