Repository infrawatch/documentation, pull requests merged in 2022-04, with the labels that each got.

#381 Fix syntax for bullet list
  common/collectd/ref_collectd-plugins.adoc
Labels: needs-backport, 1.4

#382 Fix syntax for bullet list (#381)
  common/collectd/ref_collectd-plugins.adoc
Labels: cherry-pick, 1.4

#383 Increase the send queue limit to avoid metrics
  common/collectd/ref_collectd-plugins.adoc
  doc-Service-Telemetry-Framework/modules/proc_creating-the-base-configuration-for-stf.adoc
Labels: ready for tech writer, needs-backport, 1.4, 1.5
